title: FortiGate を Ansible で。　 # website title
logo: "/images/フォー.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Ansibleを使ってFortiGateを操るためのビギナー向けチュートリアルです。
  <br><br>
  も・く・じ 
  <br><br>
  <a href="....">序. はじめに</a><br>
  <a href="....">0. LAB環境セットアップ</a><br>
  <a href="lab1">1. LAB1: ファイアウォールポリシーの設定</a><br>
  <a href="lab2">2. LAB2: スタティックルートの設定</a><br>
  <a href="lab3">3. LAB3: ライセンスのアップロード</a><br>
  <a href="lab4">4. LAB4: スタティックURLフィルタの設定</a><br>
  <a href="lab5">5. LAB5: Rolesの活用</a><br>
  <a href="lab6">6. LAB6: Inventoryとhttpapiモジュールの活用</a><br>
  <a href="lab7">7. LAB7: ファイアウォールポリシーのルックアップ</a><br>
  
theme: jekyll-theme-minimal
