logo: "/images/fo_log.jpg?raw=true" # your photo (or logo) here
title: 簡単レシピシリーズ<br>第1弾　 # website title
description: > # your text below (remove <br> elements if you don't need line breaks)
  Ansibleを使ってFortiGateを操るためのビギナー向けチュートリアルです。
  <br><br>
  <h4>も・く・じ</h4>
  <a href="#pro">はじめに</a><br>
  <a href="#lab0">環境セットアップ</a><br>
  <a href="#lab1">LAB1: ファイアウォールポリシーの設定</a><br>
  <a href="#lab2">LAB2: スタティックルートの設定</a><br>
  <a href="#lab3">LAB3: ライセンスのアップロード</a><br>
  <a href="#lab4">LAB4: スタティックURLフィルタの設定</a><br>
  <a href="#lab5">LAB5: Rolesの活用</a><br>
  <a href="#lab6">LAB6: Inventoryとhttpapiモジュールの活用</a><br>
  <a href="#lab7">LAB7: ファイアウォールポリシーのルックアップ</a><br>
  
theme: jekyll-theme-minimal
